// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void itemAppear_Animation( lv_obj_t *TargetObject, int delay);
void fadeInAfterLogo_Animation( lv_obj_t *TargetObject, int delay);
void removeBlack_Animation( lv_obj_t *TargetObject, int delay);
void introLogo_Animation( lv_obj_t *TargetObject, int delay);
void underLogo_Animation( lv_obj_t *TargetObject, int delay);
void jackpotAnim_Animation( lv_obj_t *TargetObject, int delay);
void diceAppear_Animation( lv_obj_t *TargetObject, int delay);
void blackjacklogo_Animation( lv_obj_t *TargetObject, int delay);
void cardPullAnim_Animation( lv_obj_t *TargetObject, int delay);
void frameAppear_Animation( lv_obj_t *TargetObject, int delay);
void animPointsBox_Animation( lv_obj_t *TargetObject, int delay);
void bjButtonsAnim_Animation( lv_obj_t *TargetObject, int delay);
void cardFlip_Animation( lv_obj_t *TargetObject, int delay);
void blackJackNotif_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_BlackLoading
void ui_BlackLoading_screen_init(void);
void ui_event_BlackLoading( lv_event_t * e);
lv_obj_t *ui_BlackLoading;
lv_obj_t *ui_introLogo;
lv_obj_t *ui_introLogo1;
// CUSTOM VARIABLES


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home( lv_event_t * e);
lv_obj_t *ui_Home;
lv_obj_t *ui_background;
lv_obj_t *ui_logo;
lv_obj_t *ui_moneyBar;
void ui_event_speakerButton( lv_event_t * e);
lv_obj_t *ui_speakerButton;
void ui_event_leftArrow( lv_event_t * e);
lv_obj_t *ui_leftArrow;
void ui_event_rightArrow( lv_event_t * e);
lv_obj_t *ui_rightArrow;
lv_obj_t *ui_menuSlide;
void ui_event_slotGameIconBtn( lv_event_t * e);
lv_obj_t *ui_slotGameIconBtn;
void ui_event_blackjackGameIconBtn( lv_event_t * e);
lv_obj_t *ui_blackjackGameIconBtn;
void ui_event_dicerollGameIconBtn( lv_event_t * e);
lv_obj_t *ui_dicerollGameIconBtn;
lv_obj_t *ui_coinAmontLabel;
// CUSTOM VARIABLES


// SCREEN: ui_Slots
void ui_Slots_screen_init(void);
void ui_event_Slots( lv_event_t * e);
lv_obj_t *ui_Slots;
lv_obj_t *ui_slotBars;
lv_obj_t *ui_slotColumn0;
lv_obj_t *ui_sevenIcon;
lv_obj_t *ui_cherryIcon;
lv_obj_t *ui_cloverIcon;
lv_obj_t *ui_heartIcon;
lv_obj_t *ui_barIcon;
lv_obj_t *ui_slotColumn1;
lv_obj_t *ui_heartIcon1;
lv_obj_t *ui_barIcon1;
lv_obj_t *ui_cherryIcon1;
lv_obj_t *ui_sevenIcon1;
lv_obj_t *ui_cloverIcon1;
lv_obj_t *ui_slotColumn2;
lv_obj_t *ui_cloverIcon2;
lv_obj_t *ui_sevenIcon2;
lv_obj_t *ui_heartIcon2;
lv_obj_t *ui_barIcon2;
lv_obj_t *ui_cherryIcon2;
lv_obj_t *ui_actionBar;
void ui_event_spinBtn( lv_event_t * e);
lv_obj_t *ui_spinBtn;
lv_obj_t *ui_betBar;
void ui_event_minusBtn( lv_event_t * e);
lv_obj_t *ui_minusBtn;
lv_obj_t *ui_divider;
void ui_event_plusBtn( lv_event_t * e);
lv_obj_t *ui_plusBtn;
void ui_event_slotsLogo( lv_event_t * e);
lv_obj_t *ui_slotsLogo;
void ui_event_backButtonSlots( lv_event_t * e);
lv_obj_t *ui_backButtonSlots;
lv_obj_t *ui_moneyBarSlots;
lv_obj_t *ui_coinAmountLabelSlots;
lv_obj_t *ui_betAmountSlots;
lv_obj_t *ui_jackpotImg;
// CUSTOM VARIABLES


// SCREEN: ui_BlackJack
void ui_BlackJack_screen_init(void);
void ui_event_BlackJack( lv_event_t * e);
lv_obj_t *ui_BlackJack;
lv_obj_t *ui_backgroundBlackJack;
void ui_event_backButtonSlots2( lv_event_t * e);
lv_obj_t *ui_backButtonSlots2;
lv_obj_t *ui_moneyBarSlots2;
lv_obj_t *ui_betAmountBlackJack;
lv_obj_t *ui_coinAmountLabelBlackJack;
lv_obj_t *ui_blackJackLogo;
lv_obj_t *ui_pointsBar;
lv_obj_t *ui_pointsboxDealer;
lv_obj_t *ui_dealercard1;
lv_obj_t *ui_dealercard2;
lv_obj_t *ui_dealercard3;
lv_obj_t *ui_dealercard4;
lv_obj_t *ui_dealercard5;
lv_obj_t *ui_playercardsframe;
lv_obj_t *ui_pointsboxPlayer;
void ui_event_standBtn( lv_event_t * e);
lv_obj_t *ui_standBtn;
void ui_event_hitBtn( lv_event_t * e);
lv_obj_t *ui_hitBtn;
lv_obj_t *ui_dealerPoints;
lv_obj_t *ui_playerPoints;
lv_obj_t *ui_playerCard1;
lv_obj_t *ui_playerCard2;
lv_obj_t *ui_playerCard3;
lv_obj_t *ui_playerCard4;
lv_obj_t *ui_playerCard5;
void ui_event_plusBetBlackJackBtn( lv_event_t * e);
lv_obj_t *ui_plusBetBlackJackBtn;
void ui_event_minusBetBlackJackBtn( lv_event_t * e);
lv_obj_t *ui_minusBetBlackJackBtn;
lv_obj_t *ui_bjnotf;
lv_obj_t *ui_losenotf;
lv_obj_t *ui_winnotf;
// CUSTOM VARIABLES


// SCREEN: ui_DiceRoll
void ui_DiceRoll_screen_init(void);
void ui_event_DiceRoll( lv_event_t * e);
lv_obj_t *ui_DiceRoll;
lv_obj_t *ui_diceRollBack;
void ui_event_backButtonDiceRoll( lv_event_t * e);
lv_obj_t *ui_backButtonDiceRoll;
lv_obj_t *ui_moneyBarDiceRoll;
lv_obj_t *ui_coinAmountLabelDiceRoll;
lv_obj_t *ui_betAmountDiceRoll;
lv_obj_t *ui_d11;
lv_obj_t *ui_d12;
lv_obj_t *ui_d13;
lv_obj_t *ui_d14;
lv_obj_t *ui_d15;
lv_obj_t *ui_d16;
lv_obj_t *ui_d21;
lv_obj_t *ui_d22;
lv_obj_t *ui_d23;
lv_obj_t *ui_d24;
lv_obj_t *ui_d25;
lv_obj_t *ui_d26;
void ui_event_rollDiceBtn( lv_event_t * e);
lv_obj_t *ui_rollDiceBtn;
void ui_event_plusBetDiceRoll( lv_event_t * e);
lv_obj_t *ui_plusBetDiceRoll;
void ui_event_minusBetDiceRoll( lv_event_t * e);
lv_obj_t *ui_minusBetDiceRoll;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t *ui_imgset_1214590094[13] = {&ui_img_2057722816, &ui_img_1853341697, &ui_img_417965468, &ui_img_2119927969, &ui_img_1038198790, &ui_img_43530389, &ui_img_1391845840, &ui_img_1077688739, &ui_img_2135549378, &ui_img_2057723841, &ui_img_2057729214, &ui_img_2057730239, &ui_img_2057727164};
const lv_image_dsc_t *ui_imgset_1214590089[13] = {&ui_img_68789583, &ui_img_1293794150, &ui_img_1919443967, &ui_img_162370108, &ui_img_919359071, &ui_img_516017158, &ui_img_565712021, &ui_img_259635800, &ui_img_1341364979, &ui_img_68790608, &ui_img_68795981, &ui_img_68797006, &ui_img_68793931};
const lv_image_dsc_t *ui_imgset_1214590101[13] = {&ui_img_693209757, &ui_img_1661094818, &ui_img_1552143299, &ui_img_470414120, &ui_img_611315059, &ui_img_824061170, &ui_img_257668009, &ui_img_892420028, &ui_img_189309151, &ui_img_693208732, &ui_img_693203359, &ui_img_693202334, &ui_img_693205409};
const lv_image_dsc_t *ui_imgset_1214590110[13] = {&ui_img_1913133936, &ui_img_1775697841, &ui_img_340321612, &ui_img_2097395471, &ui_img_1115842646, &ui_img_34113467, &ui_img_1469489696, &ui_img_1000044883, &ui_img_2081774062, &ui_img_1913134961, &ui_img_1913140334, &ui_img_1913141359, &ui_img_1913138284};
const lv_image_dsc_t *ui_imgset_d[6] = {&ui_img_d1_png, &ui_img_d2_png, &ui_img_d3_png, &ui_img_d4_png, &ui_img_d5_png, &ui_img_d6_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void itemAppear_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, 20, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_1);

}
void fadeInAfterLogo_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1600);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 1 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 1600 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}
void removeBlack_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}
void introLogo_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 1, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 100 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_1, -150, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 100 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_1);

}
void underLogo_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 600);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, 5, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_1);

}
void jackpotAnim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 1, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 2000 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 1);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_2, 0, 0 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_2, delay + 2500 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_2);

}
void diceAppear_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 400, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 700);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_1, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 550);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_2, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_2);

}
void blackjacklogo_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 250 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 1 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 800);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 250, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 600 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}
void cardPullAnim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 40, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_1, 90, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 300);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_2, -5, 0 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_2);
ui_anim_user_data_t *PropertyAnimation_3_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_3_user_data->target = TargetObject;
PropertyAnimation_3_user_data->val = -1;
lv_anim_t PropertyAnimation_3;
lv_anim_init(&PropertyAnimation_3);
lv_anim_set_time(&PropertyAnimation_3, 200);
lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_3, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_3, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_3, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_3, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_3, 0);
lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
lv_anim_set_early_apply( &PropertyAnimation_3, false );
lv_anim_start(&PropertyAnimation_3);

}
void frameAppear_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -10, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}
void animPointsBox_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void bjButtonsAnim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void cardFlip_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 0, 80 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_1, 0, -80 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 300 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 200);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_2, 0, 30 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_2);
ui_anim_user_data_t *PropertyAnimation_3_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_3_user_data->target = TargetObject;
PropertyAnimation_3_user_data->val = -1;
lv_anim_t PropertyAnimation_3;
lv_anim_init(&PropertyAnimation_3);
lv_anim_set_time(&PropertyAnimation_3, 200);
lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_3, 0, -30 );
lv_anim_set_path_cb( &PropertyAnimation_3, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_3, delay + 300 );
lv_anim_set_deleted_cb( &PropertyAnimation_3, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_3, 0);
lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
lv_anim_set_early_apply( &PropertyAnimation_3, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_3, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_3);

}
void blackJackNotif_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, -200, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 400);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_1, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 400);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_2, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
lv_anim_start(&PropertyAnimation_2);
ui_anim_user_data_t *PropertyAnimation_3_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_3_user_data->target = TargetObject;
PropertyAnimation_3_user_data->val = -1;
lv_anim_t PropertyAnimation_3;
lv_anim_init(&PropertyAnimation_3);
lv_anim_set_time(&PropertyAnimation_3, 300);
lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_3, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_3, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_3, delay + 2000 );
lv_anim_set_deleted_cb( &PropertyAnimation_3, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_3, 0);
lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
lv_anim_set_early_apply( &PropertyAnimation_3, false );
lv_anim_start(&PropertyAnimation_3);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_BlackLoading( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 1300, 4000, &ui_Home_screen_init);
      introLogo_Animation(ui_introLogo, 0);
      playIntroLogoSound( e );
      underLogo_Animation(ui_introLogo1, 1250);
}
}

void ui_event_Home( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      homeScreenLoad( e );
}
}

void ui_event_speakerButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      spkButton( e );
}
}

void ui_event_leftArrow( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      leftArrowPressed( e );
}
}

void ui_event_rightArrow( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      rightArrowPressed( e );
}
}

void ui_event_slotGameIconBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Slots, LV_SCR_LOAD_ANIM_FADE_ON, 600, 0, &ui_Slots_screen_init);
      homeGameButton1( e );
}
}

void ui_event_blackjackGameIconBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BlackJack, LV_SCR_LOAD_ANIM_FADE_ON, 600, 0, &ui_BlackJack_screen_init);
      homeGameButton2( e );
}
}

void ui_event_dicerollGameIconBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_DiceRoll, LV_SCR_LOAD_ANIM_FADE_ON, 600, 0, &ui_DiceRoll_screen_init);
      homeGameButton3( e );
}
}

void ui_event_Slots( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      itemAppear_Animation(ui_slotsLogo, 200);
      fadeInAfterLogo_Animation(ui_backButtonSlots, 0);
      fadeInAfterLogo_Animation(ui_plusBtn, 0);
      fadeInAfterLogo_Animation(ui_divider, 0);
      fadeInAfterLogo_Animation(ui_minusBtn, 0);
      fadeInAfterLogo_Animation(ui_betBar, 0);
      fadeInAfterLogo_Animation(ui_spinBtn, 0);
      fadeInAfterLogo_Animation(ui_actionBar, 0);
      fadeInAfterLogo_Animation(ui_slotBars, 0);
      fadeInAfterLogo_Animation(ui_moneyBarSlots, 0);
      fadeInAfterLogo_Animation(ui_coinAmountLabelSlots, 0);
      fadeInAfterLogo_Animation(ui_betAmountSlots, 0);
      fadeInAfterLogo_Animation(ui_slotColumn1, 0);
      fadeInAfterLogo_Animation(ui_slotColumn0, 0);
      fadeInAfterLogo_Animation(ui_slotColumn2, 0);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      slotsMoneyBarLoaded( e );
      betAmountLoaded( e );
}
}

void ui_event_spinBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      spinSlotBtn( e );
}
}

void ui_event_minusBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      minusBetSlots( e );
}
}

void ui_event_plusBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      plusBetSlots( e );
}
}

void ui_event_slotsLogo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      fadeInAfterLogo_Animation(ui_slotsLogo, 0);
}
}

void ui_event_backButtonSlots( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}

void ui_event_BlackJack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      blackJackLoaded( e );
      blackjacklogo_Animation(ui_blackJackLogo, 0);
      cardPullAnim_Animation(ui_dealercard1, 1500);
      cardPullAnim_Animation(ui_dealercard2, 2000);
      frameAppear_Animation(ui_pointsBar, 2300);
      animPointsBox_Animation(ui_pointsboxDealer, 2500);
      animPointsBox_Animation(ui_pointsboxPlayer, 3300);
      frameAppear_Animation(ui_playercardsframe, 3000);
      bjButtonsAnim_Animation(ui_standBtn, 3900);
      bjButtonsAnim_Animation(ui_hitBtn, 3800);
      animPointsBox_Animation(ui_playerPoints, 3300);
      animPointsBox_Animation(ui_dealerPoints, 2500);
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      blackJackUnloaded( e );
}
}

void ui_event_backButtonSlots2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}

void ui_event_standBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      standBtnClicked( e );
}
}

void ui_event_hitBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      hitBtnClicked( e );
}
}

void ui_event_plusBetBlackJackBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      plusBetBlackJack( e );
}
}

void ui_event_minusBetBlackJackBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      minusBetBlackJack( e );
}
}

void ui_event_DiceRoll( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      diceAppear_Animation(ui_d23, 2000);
      diceAppear_Animation(ui_d15, 2000);
      diceRollScreenLoaded( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      diceRollScreenUnloaded( e );
}
}

void ui_event_backButtonDiceRoll( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}

void ui_event_rollDiceBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      rollDiceBtn( e );
}
}

void ui_event_plusBetDiceRoll( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      plusBetDiceBtn( e );
}
}

void ui_event_minusBetDiceRoll( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      minusBetDiceRoll( e );
}
}

void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      itemAppear_Animation(ui_logo, 0);
      fadeInAfterLogo_Animation(ui_menuSlide, 0);
      fadeInAfterLogo_Animation(ui_leftArrow, 0);
      fadeInAfterLogo_Animation(ui_rightArrow, 0);
      fadeInAfterLogo_Animation(ui_moneyBar, 0);
      fadeInAfterLogo_Animation(ui_speakerButton, 0);
      removeBlack_Animation(ui_Home, 0);
      fadeInAfterLogo_Animation(ui_coinAmontLabel, 0);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_BlackLoading_screen_init();
ui_Home_screen_init();
ui_Slots_screen_init();
ui_BlackJack_screen_init();
ui_DiceRoll_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_BlackLoading);
}
