// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void itemAppear_Animation( lv_obj_t *TargetObject, int delay);
void fadeInAfterLogo_Animation( lv_obj_t *TargetObject, int delay);
void removeBlack_Animation( lv_obj_t *TargetObject, int delay);
void introLogo_Animation( lv_obj_t *TargetObject, int delay);
void underLogo_Animation( lv_obj_t *TargetObject, int delay);
void jackpotAnim_Animation( lv_obj_t *TargetObject, int delay);
void diceAppear_Animation( lv_obj_t *TargetObject, int delay);
void blackjacklogo_Animation( lv_obj_t *TargetObject, int delay);
void cardPullAnim_Animation( lv_obj_t *TargetObject, int delay);
void frameAppear_Animation( lv_obj_t *TargetObject, int delay);
void animPointsBox_Animation( lv_obj_t *TargetObject, int delay);
void bjButtonsAnim_Animation( lv_obj_t *TargetObject, int delay);
void cardFlip_Animation( lv_obj_t *TargetObject, int delay);
void blackJackNotif_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_BlackLoading
void ui_BlackLoading_screen_init(void);
void ui_event_BlackLoading( lv_event_t * e);
extern lv_obj_t *ui_BlackLoading;
extern lv_obj_t *ui_introLogo;
extern lv_obj_t *ui_introLogo1;
// CUSTOM VARIABLES

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home( lv_event_t * e);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_background;
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_moneyBar;
void ui_event_speakerButton( lv_event_t * e);
extern lv_obj_t *ui_speakerButton;
void ui_event_leftArrow( lv_event_t * e);
extern lv_obj_t *ui_leftArrow;
void ui_event_rightArrow( lv_event_t * e);
extern lv_obj_t *ui_rightArrow;
extern lv_obj_t *ui_menuSlide;
void ui_event_slotGameIconBtn( lv_event_t * e);
extern lv_obj_t *ui_slotGameIconBtn;
void ui_event_blackjackGameIconBtn( lv_event_t * e);
extern lv_obj_t *ui_blackjackGameIconBtn;
void ui_event_dicerollGameIconBtn( lv_event_t * e);
extern lv_obj_t *ui_dicerollGameIconBtn;
extern lv_obj_t *ui_coinAmontLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Slots
void ui_Slots_screen_init(void);
void ui_event_Slots( lv_event_t * e);
extern lv_obj_t *ui_Slots;
extern lv_obj_t *ui_slotBars;
extern lv_obj_t *ui_slotColumn0;
extern lv_obj_t *ui_sevenIcon;
extern lv_obj_t *ui_cherryIcon;
extern lv_obj_t *ui_cloverIcon;
extern lv_obj_t *ui_heartIcon;
extern lv_obj_t *ui_barIcon;
extern lv_obj_t *ui_slotColumn1;
extern lv_obj_t *ui_heartIcon1;
extern lv_obj_t *ui_barIcon1;
extern lv_obj_t *ui_cherryIcon1;
extern lv_obj_t *ui_sevenIcon1;
extern lv_obj_t *ui_cloverIcon1;
extern lv_obj_t *ui_slotColumn2;
extern lv_obj_t *ui_cloverIcon2;
extern lv_obj_t *ui_sevenIcon2;
extern lv_obj_t *ui_heartIcon2;
extern lv_obj_t *ui_barIcon2;
extern lv_obj_t *ui_cherryIcon2;
extern lv_obj_t *ui_actionBar;
void ui_event_spinBtn( lv_event_t * e);
extern lv_obj_t *ui_spinBtn;
extern lv_obj_t *ui_betBar;
void ui_event_minusBtn( lv_event_t * e);
extern lv_obj_t *ui_minusBtn;
extern lv_obj_t *ui_divider;
void ui_event_plusBtn( lv_event_t * e);
extern lv_obj_t *ui_plusBtn;
void ui_event_slotsLogo( lv_event_t * e);
extern lv_obj_t *ui_slotsLogo;
void ui_event_backButtonSlots( lv_event_t * e);
extern lv_obj_t *ui_backButtonSlots;
extern lv_obj_t *ui_moneyBarSlots;
extern lv_obj_t *ui_coinAmountLabelSlots;
extern lv_obj_t *ui_betAmountSlots;
extern lv_obj_t *ui_jackpotImg;
// CUSTOM VARIABLES

// SCREEN: ui_BlackJack
void ui_BlackJack_screen_init(void);
void ui_event_BlackJack( lv_event_t * e);
extern lv_obj_t *ui_BlackJack;
extern lv_obj_t *ui_backgroundBlackJack;
void ui_event_backButtonSlots2( lv_event_t * e);
extern lv_obj_t *ui_backButtonSlots2;
extern lv_obj_t *ui_moneyBarSlots2;
extern lv_obj_t *ui_betAmountBlackJack;
extern lv_obj_t *ui_coinAmountLabelBlackJack;
extern lv_obj_t *ui_blackJackLogo;
extern lv_obj_t *ui_pointsBar;
extern lv_obj_t *ui_pointsboxDealer;
extern lv_obj_t *ui_dealercard1;
extern lv_obj_t *ui_dealercard2;
extern lv_obj_t *ui_dealercard3;
extern lv_obj_t *ui_dealercard4;
extern lv_obj_t *ui_dealercard5;
extern lv_obj_t *ui_playercardsframe;
extern lv_obj_t *ui_pointsboxPlayer;
void ui_event_standBtn( lv_event_t * e);
extern lv_obj_t *ui_standBtn;
void ui_event_hitBtn( lv_event_t * e);
extern lv_obj_t *ui_hitBtn;
extern lv_obj_t *ui_dealerPoints;
extern lv_obj_t *ui_playerPoints;
extern lv_obj_t *ui_playerCard1;
extern lv_obj_t *ui_playerCard2;
extern lv_obj_t *ui_playerCard3;
extern lv_obj_t *ui_playerCard4;
extern lv_obj_t *ui_playerCard5;
void ui_event_plusBetBlackJackBtn( lv_event_t * e);
extern lv_obj_t *ui_plusBetBlackJackBtn;
void ui_event_minusBetBlackJackBtn( lv_event_t * e);
extern lv_obj_t *ui_minusBetBlackJackBtn;
extern lv_obj_t *ui_bjnotf;
extern lv_obj_t *ui_losenotf;
extern lv_obj_t *ui_winnotf;
// CUSTOM VARIABLES

// SCREEN: ui_DiceRoll
void ui_DiceRoll_screen_init(void);
void ui_event_DiceRoll( lv_event_t * e);
extern lv_obj_t *ui_DiceRoll;
extern lv_obj_t *ui_diceRollBack;
void ui_event_backButtonDiceRoll( lv_event_t * e);
extern lv_obj_t *ui_backButtonDiceRoll;
extern lv_obj_t *ui_moneyBarDiceRoll;
extern lv_obj_t *ui_coinAmountLabelDiceRoll;
extern lv_obj_t *ui_betAmountDiceRoll;
extern lv_obj_t *ui_d11;
extern lv_obj_t *ui_d12;
extern lv_obj_t *ui_d13;
extern lv_obj_t *ui_d14;
extern lv_obj_t *ui_d15;
extern lv_obj_t *ui_d16;
extern lv_obj_t *ui_d21;
extern lv_obj_t *ui_d22;
extern lv_obj_t *ui_d23;
extern lv_obj_t *ui_d24;
extern lv_obj_t *ui_d25;
extern lv_obj_t *ui_d26;
void ui_event_rollDiceBtn( lv_event_t * e);
extern lv_obj_t *ui_rollDiceBtn;
void ui_event_plusBetDiceRoll( lv_event_t * e);
extern lv_obj_t *ui_plusBetDiceRoll;
void ui_event_minusBetDiceRoll( lv_event_t * e);
extern lv_obj_t *ui_minusBetDiceRoll;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_imco_logo_png);   // assets/imco_logo.png
LV_IMG_DECLARE( ui_img_imco_under_png);   // assets/imco_under.png
LV_IMG_DECLARE( ui_img_back_dith_png);   // assets/back_dith.png
LV_IMG_DECLARE( ui_img_logo_bicubic_cmooth_png);   // assets/logo_bicubic_cmooth.png
LV_IMG_DECLARE( ui_img_money_bar_png);   // assets/money_bar.png
LV_IMG_DECLARE( ui_img_spk_png);   // assets/spk.png
LV_IMG_DECLARE( ui_img_spk_mute_png);   // assets/spk_mute.png
LV_IMG_DECLARE( ui_img_arrow_left_png);   // assets/arrow_left.png
LV_IMG_DECLARE( ui_img_arrow_right_png);   // assets/arrow_right.png
LV_IMG_DECLARE( ui_img_slots_png);   // assets/slots.png
LV_IMG_DECLARE( ui_img_black_jack_png);   // assets/black_jack.png
LV_IMG_DECLARE( ui_img_dice_roll_png);   // assets/dice_roll.png
LV_IMG_DECLARE( ui_img_slots_back_png);   // assets/slots_back.png
LV_IMG_DECLARE( ui_img_slot_bars_png);   // assets/slot_bars.png
LV_IMG_DECLARE( ui_img_seven_png);   // assets/seven.png
LV_IMG_DECLARE( ui_img_cherry_png);   // assets/cherry.png
LV_IMG_DECLARE( ui_img_clover_png);   // assets/clover.png
LV_IMG_DECLARE( ui_img_heart_png);   // assets/heart.png
LV_IMG_DECLARE( ui_img_bar_png);   // assets/bar.png
LV_IMG_DECLARE( ui_img_action_bar_png);   // assets/action_bar.png
LV_IMG_DECLARE( ui_img_spin_red_png);   // assets/spin_red.png
LV_IMG_DECLARE( ui_img_spin_gray_png);   // assets/spin_gray.png
LV_IMG_DECLARE( ui_img_bet_bar_png);   // assets/bet_bar.png
LV_IMG_DECLARE( ui_img_minus_btn_png);   // assets/minus_btn.png
LV_IMG_DECLARE( ui_img_divder_png);   // assets/divder.png
LV_IMG_DECLARE( ui_img_plus_btn_png);   // assets/plus_btn.png
LV_IMG_DECLARE( ui_img_slot_logo_png);   // assets/slot_logo.png
LV_IMG_DECLARE( ui_img_back_btn_png);   // assets/back_btn.png
LV_IMG_DECLARE( ui_img_back_btn_dis_png);   // assets/back_btn_dis.png
LV_IMG_DECLARE( ui_img_jackpotwin_png);   // assets/jackpotwin.png
LV_IMG_DECLARE( ui_img_backbj_png);   // assets/backBJ.png
LV_IMG_DECLARE( ui_img_bjlogo_png);   // assets/bjlogo.png
LV_IMG_DECLARE( ui_img_barpoints_png);   // assets/barpoints.png
LV_IMG_DECLARE( ui_img_boxpoints_png);   // assets/boxpoints.png
LV_IMG_DECLARE( ui_img_backcard_png);   // assets/backcard.png
LV_IMG_DECLARE( ui_img_pointbarplayer_png);   // assets/pointbarplayer.png
LV_IMG_DECLARE( ui_img_standbtn_png);   // assets/standbtn.png
LV_IMG_DECLARE( ui_img_hitbtn_png);   // assets/hitbtn.png
LV_IMG_DECLARE( ui_img_blackjacknotf_png);   // assets/blackjacknotf.png
LV_IMG_DECLARE( ui_img_losenotf_png);   // assets/losenotf.png
LV_IMG_DECLARE( ui_img_winnotf_png);   // assets/winnotf.png
LV_IMG_DECLARE( ui_img_dicerollback_png);   // assets/dicerollback.png
LV_IMG_DECLARE( ui_img_d1_png);   // assets/d1.png
LV_IMG_DECLARE( ui_img_d2_png);   // assets/d2.png
LV_IMG_DECLARE( ui_img_d3_png);   // assets/d3.png
LV_IMG_DECLARE( ui_img_d4_png);   // assets/d4.png
LV_IMG_DECLARE( ui_img_d5_png);   // assets/d5.png
LV_IMG_DECLARE( ui_img_d6_png);   // assets/d6.png
LV_IMG_DECLARE( ui_img_2057722816);   // assets/C-10.png
LV_IMG_DECLARE( ui_img_1853341697);   // assets/C-2.png
LV_IMG_DECLARE( ui_img_417965468);   // assets/C-3.png
LV_IMG_DECLARE( ui_img_2119927969);   // assets/C-4.png
LV_IMG_DECLARE( ui_img_1038198790);   // assets/C-5.png
LV_IMG_DECLARE( ui_img_43530389);   // assets/C-6.png
LV_IMG_DECLARE( ui_img_1391845840);   // assets/C-7.png
LV_IMG_DECLARE( ui_img_1077688739);   // assets/C-8.png
LV_IMG_DECLARE( ui_img_2135549378);   // assets/C-9.png
LV_IMG_DECLARE( ui_img_68789583);   // assets/D-10.png
LV_IMG_DECLARE( ui_img_1293794150);   // assets/D-2.png
LV_IMG_DECLARE( ui_img_1919443967);   // assets/D-3.png
LV_IMG_DECLARE( ui_img_162370108);   // assets/D-4.png
LV_IMG_DECLARE( ui_img_919359071);   // assets/D-5.png
LV_IMG_DECLARE( ui_img_516017158);   // assets/D-6.png
LV_IMG_DECLARE( ui_img_565712021);   // assets/D-7.png
LV_IMG_DECLARE( ui_img_259635800);   // assets/D-8.png
LV_IMG_DECLARE( ui_img_1341364979);   // assets/D-9.png
LV_IMG_DECLARE( ui_img_693209757);   // assets/H-10.png
LV_IMG_DECLARE( ui_img_1661094818);   // assets/H-2.png
LV_IMG_DECLARE( ui_img_1552143299);   // assets/H-3.png
LV_IMG_DECLARE( ui_img_470414120);   // assets/H-4.png
LV_IMG_DECLARE( ui_img_611315059);   // assets/H-5.png
LV_IMG_DECLARE( ui_img_824061170);   // assets/H-6.png
LV_IMG_DECLARE( ui_img_257668009);   // assets/H-7.png
LV_IMG_DECLARE( ui_img_892420028);   // assets/H-8.png
LV_IMG_DECLARE( ui_img_189309151);   // assets/H-9.png
LV_IMG_DECLARE( ui_img_1913133936);   // assets/S-10.png
LV_IMG_DECLARE( ui_img_1775697841);   // assets/S-2.png
LV_IMG_DECLARE( ui_img_340321612);   // assets/S-3.png
LV_IMG_DECLARE( ui_img_2097395471);   // assets/S-4.png
LV_IMG_DECLARE( ui_img_1115842646);   // assets/S-5.png
LV_IMG_DECLARE( ui_img_34113467);   // assets/S-6.png
LV_IMG_DECLARE( ui_img_1469489696);   // assets/S-7.png
LV_IMG_DECLARE( ui_img_1000044883);   // assets/S-8.png
LV_IMG_DECLARE( ui_img_2081774062);   // assets/S-9.png
LV_IMG_DECLARE( ui_img_2057723841);   // assets/C-11.png
LV_IMG_DECLARE( ui_img_2057729214);   // assets/C-12.png
LV_IMG_DECLARE( ui_img_2057730239);   // assets/C-13.png
LV_IMG_DECLARE( ui_img_2057727164);   // assets/C-14.png
LV_IMG_DECLARE( ui_img_68790608);   // assets/D-11.png
LV_IMG_DECLARE( ui_img_68795981);   // assets/D-12.png
LV_IMG_DECLARE( ui_img_68797006);   // assets/D-13.png
LV_IMG_DECLARE( ui_img_68793931);   // assets/D-14.png
LV_IMG_DECLARE( ui_img_693208732);   // assets/H-11.png
LV_IMG_DECLARE( ui_img_693203359);   // assets/H-12.png
LV_IMG_DECLARE( ui_img_693202334);   // assets/H-13.png
LV_IMG_DECLARE( ui_img_693205409);   // assets/H-14.png
LV_IMG_DECLARE( ui_img_1913134961);   // assets/S-11.png
LV_IMG_DECLARE( ui_img_1913140334);   // assets/S-12.png
LV_IMG_DECLARE( ui_img_1913141359);   // assets/S-13.png
LV_IMG_DECLARE( ui_img_1913138284);   // assets/S-14.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
