// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_BlackLoading_screen_init(void)
{
ui_BlackLoading = lv_obj_create(NULL);
lv_obj_remove_flag( ui_BlackLoading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BlackLoading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BlackLoading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_introLogo = lv_image_create(ui_BlackLoading);
lv_image_set_src(ui_introLogo, &ui_img_imco_logo_png);
lv_obj_set_width( ui_introLogo, lv_pct(80));
lv_obj_set_height( ui_introLogo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_introLogo, -1 );
lv_obj_set_y( ui_introLogo, -8 );
lv_obj_set_align( ui_introLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_introLogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_introLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_introLogo,120);
lv_obj_set_style_opa(ui_introLogo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_introLogo1 = lv_image_create(ui_BlackLoading);
lv_image_set_src(ui_introLogo1, &ui_img_imco_under_png);
lv_obj_set_width( ui_introLogo1, 192);
lv_obj_set_height( ui_introLogo1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_introLogo1, -1 );
lv_obj_set_y( ui_introLogo1, -8 );
lv_obj_set_align( ui_introLogo1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_introLogo1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_introLogo1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_introLogo1,120);
lv_obj_set_style_opa(ui_introLogo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BlackLoading, ui_event_BlackLoading, LV_EVENT_ALL, NULL);

}
