// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_BlackJack_screen_init(void)
{
ui_BlackJack = lv_obj_create(NULL);
lv_obj_remove_flag( ui_BlackJack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BlackJack, lv_color_hex(0x50DA5C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BlackJack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backgroundBlackJack = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_backgroundBlackJack, &ui_img_backbj_png);
lv_obj_set_width( ui_backgroundBlackJack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backgroundBlackJack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backgroundBlackJack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_backgroundBlackJack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_backgroundBlackJack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backButtonSlots2 = lv_imagebutton_create(ui_BlackJack);
lv_imagebutton_set_src(ui_backButtonSlots2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back_btn_png, NULL);
lv_imagebutton_set_src(ui_backButtonSlots2, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_back_btn_dis_png, NULL);
lv_obj_set_height( ui_backButtonSlots2, 31);
lv_obj_set_width( ui_backButtonSlots2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_backButtonSlots2, -92 );
lv_obj_set_y( ui_backButtonSlots2, 128 );
lv_obj_set_align( ui_backButtonSlots2, LV_ALIGN_CENTER );
lv_obj_set_style_image_recolor(ui_backButtonSlots2, lv_color_hex(0x252525), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_image_recolor_opa(ui_backButtonSlots2, 120, LV_PART_MAIN| LV_STATE_DISABLED);

ui_moneyBarSlots2 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_moneyBarSlots2, &ui_img_money_bar_png);
lv_obj_set_width( ui_moneyBarSlots2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moneyBarSlots2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moneyBarSlots2, 50 );
lv_obj_set_y( ui_moneyBarSlots2, 128 );
lv_obj_set_align( ui_moneyBarSlots2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_moneyBarSlots2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_moneyBarSlots2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_betAmountBlackJack = ui_betAmountSlots_create(ui_BlackJack);
lv_obj_set_x( ui_betAmountBlackJack, -46 );
lv_obj_set_y( ui_betAmountBlackJack, 79 );

ui_coinAmountLabelBlackJack = ui_coinAmountLabelSlots_create(ui_BlackJack);
lv_obj_set_x( ui_coinAmountLabelBlackJack, 34 );
lv_obj_set_y( ui_coinAmountLabelBlackJack, 129 );

ui_blackJackLogo = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_blackJackLogo, &ui_img_bjlogo_png);
lv_obj_set_width( ui_blackJackLogo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_blackJackLogo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_blackJackLogo, -2 );
lv_obj_set_y( ui_blackJackLogo, -90 );
lv_obj_set_align( ui_blackJackLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_blackJackLogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_blackJackLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_blackJackLogo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pointsBar = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_pointsBar, &ui_img_barpoints_png);
lv_obj_set_width( ui_pointsBar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pointsBar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pointsBar, 0 );
lv_obj_set_y( ui_pointsBar, -63 );
lv_obj_set_align( ui_pointsBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pointsBar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_pointsBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_pointsBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pointsboxDealer = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_pointsboxDealer, &ui_img_boxpoints_png);
lv_obj_set_width( ui_pointsboxDealer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pointsboxDealer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pointsboxDealer, 0 );
lv_obj_set_y( ui_pointsboxDealer, -58 );
lv_obj_set_align( ui_pointsboxDealer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pointsboxDealer, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_pointsboxDealer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_pointsboxDealer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealercard1 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_dealercard1, &ui_img_backcard_png);
lv_obj_set_width( ui_dealercard1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealercard1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealercard1, -13 );
lv_obj_set_y( ui_dealercard1, -104 );
lv_obj_set_align( ui_dealercard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dealercard1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_dealercard1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_dealercard1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealercard2 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_dealercard2, &ui_img_backcard_png);
lv_obj_set_width( ui_dealercard2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealercard2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealercard2, 9 );
lv_obj_set_y( ui_dealercard2, -104 );
lv_obj_set_align( ui_dealercard2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dealercard2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_dealercard2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_dealercard2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealercard3 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_dealercard3, &ui_img_backcard_png);
lv_obj_set_width( ui_dealercard3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealercard3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealercard3, 31 );
lv_obj_set_y( ui_dealercard3, -104 );
lv_obj_set_align( ui_dealercard3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dealercard3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_dealercard3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_dealercard3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealercard4 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_dealercard4, &ui_img_backcard_png);
lv_obj_set_width( ui_dealercard4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealercard4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealercard4, 52 );
lv_obj_set_y( ui_dealercard4, -104 );
lv_obj_set_align( ui_dealercard4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dealercard4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_dealercard4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_dealercard4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealercard5 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_dealercard5, &ui_img_backcard_png);
lv_obj_set_width( ui_dealercard5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealercard5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealercard5, 72 );
lv_obj_set_y( ui_dealercard5, -104 );
lv_obj_set_align( ui_dealercard5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dealercard5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_dealercard5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_dealercard5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playercardsframe = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playercardsframe, &ui_img_pointbarplayer_png);
lv_obj_set_width( ui_playercardsframe, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playercardsframe, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playercardsframe, 0 );
lv_obj_set_y( ui_playercardsframe, 4 );
lv_obj_set_align( ui_playercardsframe, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playercardsframe, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playercardsframe, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playercardsframe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pointsboxPlayer = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_pointsboxPlayer, &ui_img_boxpoints_png);
lv_obj_set_width( ui_pointsboxPlayer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pointsboxPlayer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pointsboxPlayer, 0 );
lv_obj_set_y( ui_pointsboxPlayer, 36 );
lv_obj_set_align( ui_pointsboxPlayer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pointsboxPlayer, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_pointsboxPlayer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_pointsboxPlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_standBtn = lv_imagebutton_create(ui_BlackJack);
lv_imagebutton_set_src(ui_standBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_standbtn_png, NULL);
lv_obj_set_height( ui_standBtn, 40);
lv_obj_set_width( ui_standBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_standBtn, -81 );
lv_obj_set_y( ui_standBtn, -45 );
lv_obj_set_align( ui_standBtn, LV_ALIGN_CENTER );
lv_obj_set_style_opa(ui_standBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hitBtn = lv_imagebutton_create(ui_BlackJack);
lv_imagebutton_set_src(ui_hitBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_hitbtn_png, NULL);
lv_obj_set_height( ui_hitBtn, 40);
lv_obj_set_width( ui_hitBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_hitBtn, -81 );
lv_obj_set_y( ui_hitBtn, 26 );
lv_obj_set_align( ui_hitBtn, LV_ALIGN_CENTER );
lv_obj_set_style_opa(ui_hitBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dealerPoints = lv_label_create(ui_BlackJack);
lv_obj_set_width( ui_dealerPoints, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dealerPoints, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dealerPoints, 0 );
lv_obj_set_y( ui_dealerPoints, -57 );
lv_obj_set_align( ui_dealerPoints, LV_ALIGN_CENTER );
lv_label_set_text(ui_dealerPoints,"0");
lv_obj_set_style_opa(ui_dealerPoints, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerPoints = lv_label_create(ui_BlackJack);
lv_obj_set_width( ui_playerPoints, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerPoints, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerPoints, 0 );
lv_obj_set_y( ui_playerPoints, 37 );
lv_obj_set_align( ui_playerPoints, LV_ALIGN_CENTER );
lv_label_set_text(ui_playerPoints,"0");
lv_obj_set_style_opa(ui_playerPoints, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerCard1 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playerCard1, &ui_img_backcard_png);
lv_obj_set_width( ui_playerCard1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerCard1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerCard1, -13 );
lv_obj_set_y( ui_playerCard1, -10 );
lv_obj_set_align( ui_playerCard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playerCard1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playerCard1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playerCard1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerCard2 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playerCard2, &ui_img_backcard_png);
lv_obj_set_width( ui_playerCard2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerCard2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerCard2, 9 );
lv_obj_set_y( ui_playerCard2, -10 );
lv_obj_set_align( ui_playerCard2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playerCard2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playerCard2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playerCard2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerCard3 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playerCard3, &ui_img_backcard_png);
lv_obj_set_width( ui_playerCard3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerCard3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerCard3, 31 );
lv_obj_set_y( ui_playerCard3, -10 );
lv_obj_set_align( ui_playerCard3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playerCard3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playerCard3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playerCard3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerCard4 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playerCard4, &ui_img_backcard_png);
lv_obj_set_width( ui_playerCard4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerCard4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerCard4, 52 );
lv_obj_set_y( ui_playerCard4, -10 );
lv_obj_set_align( ui_playerCard4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playerCard4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playerCard4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playerCard4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playerCard5 = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_playerCard5, &ui_img_backcard_png);
lv_obj_set_width( ui_playerCard5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_playerCard5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_playerCard5, 72 );
lv_obj_set_y( ui_playerCard5, -10 );
lv_obj_set_align( ui_playerCard5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_playerCard5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_playerCard5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_playerCard5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plusBetBlackJackBtn = lv_button_create(ui_BlackJack);
lv_obj_set_width( ui_plusBetBlackJackBtn, 39);
lv_obj_set_height( ui_plusBetBlackJackBtn, 38);
lv_obj_set_x( ui_plusBetBlackJackBtn, 85 );
lv_obj_set_y( ui_plusBetBlackJackBtn, 79 );
lv_obj_set_align( ui_plusBetBlackJackBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_plusBetBlackJackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_plusBetBlackJackBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_plusBetBlackJackBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minusBetBlackJackBtn = lv_button_create(ui_BlackJack);
lv_obj_set_width( ui_minusBetBlackJackBtn, 39);
lv_obj_set_height( ui_minusBetBlackJackBtn, 38);
lv_obj_set_x( ui_minusBetBlackJackBtn, 37 );
lv_obj_set_y( ui_minusBetBlackJackBtn, 79 );
lv_obj_set_align( ui_minusBetBlackJackBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_minusBetBlackJackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_minusBetBlackJackBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_minusBetBlackJackBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bjnotf = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_bjnotf, &ui_img_blackjacknotf_png);
lv_obj_set_width( ui_bjnotf, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bjnotf, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bjnotf, -2 );
lv_obj_set_y( ui_bjnotf, -25 );
lv_obj_set_align( ui_bjnotf, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bjnotf, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_bjnotf, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_bjnotf, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_losenotf = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_losenotf, &ui_img_losenotf_png);
lv_obj_set_width( ui_losenotf, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_losenotf, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_losenotf, -2 );
lv_obj_set_y( ui_losenotf, -25 );
lv_obj_set_align( ui_losenotf, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_losenotf, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_losenotf, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_losenotf, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_winnotf = lv_image_create(ui_BlackJack);
lv_image_set_src(ui_winnotf, &ui_img_winnotf_png);
lv_obj_set_width( ui_winnotf, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_winnotf, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_winnotf, -2 );
lv_obj_set_y( ui_winnotf, -25 );
lv_obj_set_align( ui_winnotf, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_winnotf, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_winnotf, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_winnotf, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_backButtonSlots2, ui_event_backButtonSlots2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_standBtn, ui_event_standBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_hitBtn, ui_event_hitBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_plusBetBlackJackBtn, ui_event_plusBetBlackJackBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_minusBetBlackJackBtn, ui_event_minusBetBlackJackBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BlackJack, ui_event_BlackJack, LV_EVENT_ALL, NULL);

}
