// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


void ui_event_comp_coinAmontLabel_coinAmontLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_coinAmontLabel = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      coinsAmountHome( e );
}
}

// COMPONENT coinAmontLabel

lv_obj_t *ui_coinAmontLabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_coinAmontLabel;
cui_coinAmontLabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_coinAmontLabel, 50);
lv_obj_set_height( cui_coinAmontLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_coinAmontLabel, 34 );
lv_obj_set_y( cui_coinAmontLabel, 129 );
lv_obj_set_align( cui_coinAmontLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_coinAmontLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_coinAmontLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(cui_coinAmontLabel,"0");
lv_obj_set_style_text_align(cui_coinAmontLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_coinAmontLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_COINAMONTLABEL_NUM);
children[UI_COMP_COINAMONTLABEL_COINAMONTLABEL] = cui_coinAmontLabel;
lv_obj_add_event_cb(cui_coinAmontLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_coinAmontLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_coinAmontLabel, ui_event_comp_coinAmontLabel_coinAmontLabel, LV_EVENT_ALL, children);
ui_comp_coinAmontLabel_create_hook(cui_coinAmontLabel);
return cui_coinAmontLabel; 
}

