// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_BETAMOUNTSLOTS_H
#define _UI_COMP_BETAMOUNTSLOTS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT betAmountSlots
#define UI_COMP_BETAMOUNTSLOTS_BETAMOUNTSLOTS 0
#define _UI_COMP_BETAMOUNTSLOTS_NUM 1
lv_obj_t *ui_betAmountSlots_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
