// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT betAmountSlots

lv_obj_t *ui_betAmountSlots_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_betAmountSlots;
cui_betAmountSlots = lv_label_create(comp_parent);
lv_obj_set_width( cui_betAmountSlots, 45);
lv_obj_set_height( cui_betAmountSlots, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_betAmountSlots, -71 );
lv_obj_set_y( cui_betAmountSlots, 61 );
lv_obj_set_align( cui_betAmountSlots, LV_ALIGN_CENTER );
lv_label_set_text(cui_betAmountSlots,"0");

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BETAMOUNTSLOTS_NUM);
children[UI_COMP_BETAMOUNTSLOTS_BETAMOUNTSLOTS] = cui_betAmountSlots;
lv_obj_add_event_cb(cui_betAmountSlots, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_betAmountSlots, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_betAmountSlots_create_hook(cui_betAmountSlots);
return cui_betAmountSlots; 
}

