// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_HOOK_H
#define _SQUARELINE_PROJECT_UI_COMP_HOOK_H
#include "lvgl.h"
#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_betAmountSlots_create_hook( lv_obj_t *comp );
void ui_comp_coinAmontLabel_create_hook( lv_obj_t *comp );
void ui_comp_coinAmountLabelSlots_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
