// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT coinAmountLabelSlots

lv_obj_t *ui_coinAmountLabelSlots_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_coinAmountLabelSlots;
cui_coinAmountLabelSlots = lv_label_create(comp_parent);
lv_obj_set_width( cui_coinAmountLabelSlots, 50);
lv_obj_set_height( cui_coinAmountLabelSlots, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_coinAmountLabelSlots, 34 );
lv_obj_set_y( cui_coinAmountLabelSlots, 129 );
lv_obj_set_align( cui_coinAmountLabelSlots, LV_ALIGN_CENTER );
lv_label_set_text(cui_coinAmountLabelSlots,"0");

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_COINAMOUNTLABELSLOTS_NUM);
children[UI_COMP_COINAMOUNTLABELSLOTS_COINAMOUNTLABELSLOTS] = cui_coinAmountLabelSlots;
lv_obj_add_event_cb(cui_coinAmountLabelSlots, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_coinAmountLabelSlots, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_coinAmountLabelSlots_create_hook(cui_coinAmountLabelSlots);
return cui_coinAmountLabelSlots; 
}

