// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_DiceRoll_screen_init(void)
{
ui_DiceRoll = lv_obj_create(NULL);
lv_obj_remove_flag( ui_DiceRoll, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DiceRoll, lv_color_hex(0xAE2121), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DiceRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_DiceRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_diceRollBack = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_diceRollBack, &ui_img_dicerollback_png);
lv_obj_set_width( ui_diceRollBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_diceRollBack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_diceRollBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_diceRollBack, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_diceRollBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backButtonDiceRoll = lv_imagebutton_create(ui_DiceRoll);
lv_imagebutton_set_src(ui_backButtonDiceRoll, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back_btn_png, NULL);
lv_imagebutton_set_src(ui_backButtonDiceRoll, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_back_btn_dis_png, NULL);
lv_obj_set_height( ui_backButtonDiceRoll, 31);
lv_obj_set_width( ui_backButtonDiceRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_backButtonDiceRoll, -92 );
lv_obj_set_y( ui_backButtonDiceRoll, 128 );
lv_obj_set_align( ui_backButtonDiceRoll, LV_ALIGN_CENTER );
lv_obj_set_style_image_recolor(ui_backButtonDiceRoll, lv_color_hex(0x252525), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_image_recolor_opa(ui_backButtonDiceRoll, 120, LV_PART_MAIN| LV_STATE_DISABLED);

ui_moneyBarDiceRoll = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_moneyBarDiceRoll, &ui_img_money_bar_png);
lv_obj_set_width( ui_moneyBarDiceRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moneyBarDiceRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moneyBarDiceRoll, 50 );
lv_obj_set_y( ui_moneyBarDiceRoll, 128 );
lv_obj_set_align( ui_moneyBarDiceRoll, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_moneyBarDiceRoll, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_moneyBarDiceRoll, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_coinAmountLabelDiceRoll = ui_coinAmountLabelSlots_create(ui_DiceRoll);
lv_obj_set_x( ui_coinAmountLabelDiceRoll, 34 );
lv_obj_set_y( ui_coinAmountLabelDiceRoll, 129 );

ui_betAmountDiceRoll = ui_betAmountSlots_create(ui_DiceRoll);
lv_obj_set_x( ui_betAmountDiceRoll, -39 );
lv_obj_set_y( ui_betAmountDiceRoll, 81 );
lv_obj_set_style_text_align(ui_betAmountDiceRoll, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d11 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d11, &ui_img_d1_png);
lv_obj_set_width( ui_d11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d11, -58 );
lv_obj_set_y( ui_d11, 12 );
lv_obj_set_align( ui_d11, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d12 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d12, &ui_img_d2_png);
lv_obj_set_width( ui_d12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d12, -58 );
lv_obj_set_y( ui_d12, 12 );
lv_obj_set_align( ui_d12, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d13 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d13, &ui_img_d3_png);
lv_obj_set_width( ui_d13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d13, -58 );
lv_obj_set_y( ui_d13, 12 );
lv_obj_set_align( ui_d13, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d14 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d14, &ui_img_d4_png);
lv_obj_set_width( ui_d14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d14, -58 );
lv_obj_set_y( ui_d14, 12 );
lv_obj_set_align( ui_d14, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d15 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d15, &ui_img_d5_png);
lv_obj_set_width( ui_d15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d15, -58 );
lv_obj_set_y( ui_d15, 12 );
lv_obj_set_align( ui_d15, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d16 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d16, &ui_img_d6_png);
lv_obj_set_width( ui_d16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d16, -58 );
lv_obj_set_y( ui_d16, 12 );
lv_obj_set_align( ui_d16, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d21 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d21, &ui_img_d1_png);
lv_obj_set_width( ui_d21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d21, 54 );
lv_obj_set_y( ui_d21, 12 );
lv_obj_set_align( ui_d21, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d21, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d22 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d22, &ui_img_d2_png);
lv_obj_set_width( ui_d22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d22, 54 );
lv_obj_set_y( ui_d22, 12 );
lv_obj_set_align( ui_d22, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d22, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d22, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d23 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d23, &ui_img_d3_png);
lv_obj_set_width( ui_d23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d23, 54 );
lv_obj_set_y( ui_d23, 12 );
lv_obj_set_align( ui_d23, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d23, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d23, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d24 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d24, &ui_img_d4_png);
lv_obj_set_width( ui_d24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d24, 54 );
lv_obj_set_y( ui_d24, 12 );
lv_obj_set_align( ui_d24, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d24, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d24, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d25 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d25, &ui_img_d5_png);
lv_obj_set_width( ui_d25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d25, 54 );
lv_obj_set_y( ui_d25, 12 );
lv_obj_set_align( ui_d25, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d25, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d25, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_d26 = lv_image_create(ui_DiceRoll);
lv_image_set_src(ui_d26, &ui_img_d6_png);
lv_obj_set_width( ui_d26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_d26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_d26, 54 );
lv_obj_set_y( ui_d26, 12 );
lv_obj_set_align( ui_d26, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_d26, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_d26, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rollDiceBtn = lv_button_create(ui_DiceRoll);
lv_obj_set_width( ui_rollDiceBtn, 160);
lv_obj_set_height( ui_rollDiceBtn, 44);
lv_obj_set_x( ui_rollDiceBtn, -2 );
lv_obj_set_y( ui_rollDiceBtn, 12 );
lv_obj_set_align( ui_rollDiceBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rollDiceBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_rollDiceBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_rollDiceBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plusBetDiceRoll = lv_button_create(ui_DiceRoll);
lv_obj_set_width( ui_plusBetDiceRoll, 46);
lv_obj_set_height( ui_plusBetDiceRoll, 33);
lv_obj_set_x( ui_plusBetDiceRoll, 69 );
lv_obj_set_y( ui_plusBetDiceRoll, 81 );
lv_obj_set_align( ui_plusBetDiceRoll, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_plusBetDiceRoll, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_plusBetDiceRoll, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_plusBetDiceRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minusBetDiceRoll = lv_button_create(ui_DiceRoll);
lv_obj_set_width( ui_minusBetDiceRoll, 46);
lv_obj_set_height( ui_minusBetDiceRoll, 33);
lv_obj_set_x( ui_minusBetDiceRoll, 18 );
lv_obj_set_y( ui_minusBetDiceRoll, 81 );
lv_obj_set_align( ui_minusBetDiceRoll, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_minusBetDiceRoll, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_minusBetDiceRoll, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_minusBetDiceRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_backButtonDiceRoll, ui_event_backButtonDiceRoll, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rollDiceBtn, ui_event_rollDiceBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_plusBetDiceRoll, ui_event_plusBetDiceRoll, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_minusBetDiceRoll, ui_event_minusBetDiceRoll, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DiceRoll, ui_event_DiceRoll, LV_EVENT_ALL, NULL);

}
