// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
#include "lvgl.h"
#ifdef __cplusplus
extern "C" {
#endif

void playIntroLogoSound(lv_event_t * e);
void homeScreenLoad(lv_event_t * e);
void spkButton(lv_event_t * e);
void leftArrowPressed(lv_event_t * e);
void rightArrowPressed(lv_event_t * e);
void homeGameButton1(lv_event_t * e);
void homeGameButton2(lv_event_t * e);
void homeGameButton3(lv_event_t * e);
void coinsAmountHome(lv_event_t * e);
void slotsMoneyBarLoaded(lv_event_t * e);
void betAmountLoaded(lv_event_t * e);
void spinSlotBtn(lv_event_t * e);
void minusBetSlots(lv_event_t * e);
void plusBetSlots(lv_event_t * e);
void blackJackLoaded(lv_event_t * e);
void blackJackUnloaded(lv_event_t * e);
void standBtnClicked(lv_event_t * e);
void hitBtnClicked(lv_event_t * e);
void plusBetBlackJack(lv_event_t * e);
void minusBetBlackJack(lv_event_t * e);
void diceRollScreenLoaded(lv_event_t * e);
void diceRollScreenUnloaded(lv_event_t * e);
void rollDiceBtn(lv_event_t * e);
void plusBetDiceBtn(lv_event_t * e);
void minusBetDiceRoll(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
