// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_background = lv_image_create(ui_Home);
lv_image_set_src(ui_background, &ui_img_back_dith_png);
lv_obj_set_width( ui_background, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_background, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_background, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_logo = lv_image_create(ui_Home);
lv_image_set_src(ui_logo, &ui_img_logo_bicubic_cmooth_png);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_logo, 0 );
lv_obj_set_y( ui_logo, -103 );
lv_obj_set_align( ui_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_moneyBar = lv_image_create(ui_Home);
lv_image_set_src(ui_moneyBar, &ui_img_money_bar_png);
lv_obj_set_width( ui_moneyBar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moneyBar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moneyBar, 50 );
lv_obj_set_y( ui_moneyBar, 128 );
lv_obj_set_align( ui_moneyBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_moneyBar, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_moneyBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speakerButton = lv_imagebutton_create(ui_Home);
lv_imagebutton_set_src(ui_speakerButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_spk_png, NULL);
lv_imagebutton_set_src(ui_speakerButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_spk_mute_png, NULL);
lv_obj_set_height( ui_speakerButton, 31);
lv_obj_set_width( ui_speakerButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_speakerButton, -92 );
lv_obj_set_y( ui_speakerButton, 128 );
lv_obj_set_align( ui_speakerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speakerButton, LV_OBJ_FLAG_CHECKABLE );   /// Flags

ui_leftArrow = lv_imagebutton_create(ui_Home);
lv_imagebutton_set_src(ui_leftArrow, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrow_left_png, NULL);
lv_obj_set_height( ui_leftArrow, 25);
lv_obj_set_width( ui_leftArrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_leftArrow, -98 );
lv_obj_set_y( ui_leftArrow, 23 );
lv_obj_set_align( ui_leftArrow, LV_ALIGN_CENTER );

ui_rightArrow = lv_imagebutton_create(ui_Home);
lv_imagebutton_set_src(ui_rightArrow, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_arrow_right_png, NULL);
lv_obj_set_height( ui_rightArrow, 25);
lv_obj_set_width( ui_rightArrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_rightArrow, 94 );
lv_obj_set_y( ui_rightArrow, 23 );
lv_obj_set_align( ui_rightArrow, LV_ALIGN_CENTER );

ui_menuSlide = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_menuSlide);
lv_obj_set_width( ui_menuSlide, 150);
lv_obj_set_height( ui_menuSlide, 150);
lv_obj_set_x( ui_menuSlide, 0 );
lv_obj_set_y( ui_menuSlide, 21 );
lv_obj_set_align( ui_menuSlide, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_menuSlide,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_menuSlide, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_menuSlide, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_menuSlide, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_menuSlide, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_menuSlide, LV_DIR_HOR);

ui_slotGameIconBtn = lv_imagebutton_create(ui_menuSlide);
lv_imagebutton_set_src(ui_slotGameIconBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_slots_png, NULL);
lv_imagebutton_set_src(ui_slotGameIconBtn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_slots_png, NULL);
lv_obj_set_height( ui_slotGameIconBtn, 119);
lv_obj_set_width( ui_slotGameIconBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_slotGameIconBtn, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_slotGameIconBtn, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_slotGameIconBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags

ui_blackjackGameIconBtn = lv_imagebutton_create(ui_menuSlide);
lv_imagebutton_set_src(ui_blackjackGameIconBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_black_jack_png, NULL);
lv_obj_set_height( ui_blackjackGameIconBtn, 119);
lv_obj_set_width( ui_blackjackGameIconBtn, LV_SIZE_CONTENT);  /// 145
lv_obj_set_align( ui_blackjackGameIconBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_blackjackGameIconBtn, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_blackjackGameIconBtn, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_blackjackGameIconBtn, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_blackjackGameIconBtn, LV_DIR_HOR);

ui_dicerollGameIconBtn = lv_imagebutton_create(ui_menuSlide);
lv_imagebutton_set_src(ui_dicerollGameIconBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_dice_roll_png, NULL);
lv_obj_set_height( ui_dicerollGameIconBtn, 119);
lv_obj_set_width( ui_dicerollGameIconBtn, LV_SIZE_CONTENT);  /// 145
lv_obj_set_align( ui_dicerollGameIconBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dicerollGameIconBtn, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_dicerollGameIconBtn, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_dicerollGameIconBtn, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_dicerollGameIconBtn, LV_DIR_HOR);

ui_coinAmontLabel = ui_coinAmontLabel_create(ui_Home);
lv_obj_set_x( ui_coinAmontLabel, 34 );
lv_obj_set_y( ui_coinAmontLabel, 129 );

lv_obj_add_event_cb(ui_speakerButton, ui_event_speakerButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftArrow, ui_event_leftArrow, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rightArrow, ui_event_rightArrow, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_slotGameIconBtn, ui_event_slotGameIconBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_blackjackGameIconBtn, ui_event_blackjackGameIconBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dicerollGameIconBtn, ui_event_dicerollGameIconBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
