// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Slots_screen_init(void)
{
ui_Slots = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Slots, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_Slots, &ui_img_slots_back_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_opa(ui_Slots, 120, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_slotBars = lv_image_create(ui_Slots);
lv_image_set_src(ui_slotBars, &ui_img_slot_bars_png);
lv_obj_set_width( ui_slotBars, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_slotBars, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_slotBars, 0 );
lv_obj_set_y( ui_slotBars, -9 );
lv_obj_set_align( ui_slotBars, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_slotBars, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_slotBars, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_slotColumn0 = lv_obj_create(ui_Slots);
lv_obj_remove_style_all(ui_slotColumn0);
lv_obj_set_width( ui_slotColumn0, 61);
lv_obj_set_height( ui_slotColumn0, 101);
lv_obj_set_x( ui_slotColumn0, -69 );
lv_obj_set_y( ui_slotColumn0, -11 );
lv_obj_set_align( ui_slotColumn0, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_slotColumn0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_slotColumn0, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_slotColumn0, LV_DIR_VER);
lv_obj_set_style_pad_row(ui_slotColumn0, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_slotColumn0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sevenIcon = lv_image_create(ui_slotColumn0);
lv_image_set_src(ui_sevenIcon, &ui_img_seven_png);
lv_obj_set_width( ui_sevenIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sevenIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sevenIcon, 2 );
lv_obj_set_y( ui_sevenIcon, -120 );
lv_obj_set_align( ui_sevenIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_sevenIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_sevenIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cherryIcon = lv_image_create(ui_slotColumn0);
lv_image_set_src(ui_cherryIcon, &ui_img_cherry_png);
lv_obj_set_width( ui_cherryIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cherryIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cherryIcon, 0 );
lv_obj_set_y( ui_cherryIcon, -60 );
lv_obj_set_align( ui_cherryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cherryIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cherryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cloverIcon = lv_image_create(ui_slotColumn0);
lv_image_set_src(ui_cloverIcon, &ui_img_clover_png);
lv_obj_set_width( ui_cloverIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cloverIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_cloverIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cloverIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cloverIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heartIcon = lv_image_create(ui_slotColumn0);
lv_image_set_src(ui_heartIcon, &ui_img_heart_png);
lv_obj_set_width( ui_heartIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heartIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heartIcon, 0 );
lv_obj_set_y( ui_heartIcon, 60 );
lv_obj_set_align( ui_heartIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_heartIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_heartIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barIcon = lv_image_create(ui_slotColumn0);
lv_image_set_src(ui_barIcon, &ui_img_bar_png);
lv_obj_set_width( ui_barIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_barIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_barIcon, 0 );
lv_obj_set_y( ui_barIcon, 120 );
lv_obj_set_align( ui_barIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_barIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_barIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_slotColumn1 = lv_obj_create(ui_Slots);
lv_obj_remove_style_all(ui_slotColumn1);
lv_obj_set_width( ui_slotColumn1, 61);
lv_obj_set_height( ui_slotColumn1, 101);
lv_obj_set_x( ui_slotColumn1, 0 );
lv_obj_set_y( ui_slotColumn1, -11 );
lv_obj_set_align( ui_slotColumn1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_slotColumn1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_slotColumn1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_slotColumn1, LV_DIR_VER);
lv_obj_set_style_pad_row(ui_slotColumn1, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_slotColumn1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heartIcon1 = lv_image_create(ui_slotColumn1);
lv_image_set_src(ui_heartIcon1, &ui_img_heart_png);
lv_obj_set_width( ui_heartIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heartIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heartIcon1, 0 );
lv_obj_set_y( ui_heartIcon1, -120 );
lv_obj_set_align( ui_heartIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_heartIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_heartIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barIcon1 = lv_image_create(ui_slotColumn1);
lv_image_set_src(ui_barIcon1, &ui_img_bar_png);
lv_obj_set_width( ui_barIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_barIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_barIcon1, 0 );
lv_obj_set_y( ui_barIcon1, -60 );
lv_obj_set_align( ui_barIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_barIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_barIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cherryIcon1 = lv_image_create(ui_slotColumn1);
lv_image_set_src(ui_cherryIcon1, &ui_img_cherry_png);
lv_obj_set_width( ui_cherryIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cherryIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_cherryIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cherryIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cherryIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sevenIcon1 = lv_image_create(ui_slotColumn1);
lv_image_set_src(ui_sevenIcon1, &ui_img_seven_png);
lv_obj_set_width( ui_sevenIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sevenIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sevenIcon1, 2 );
lv_obj_set_y( ui_sevenIcon1, 60 );
lv_obj_set_align( ui_sevenIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_sevenIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_sevenIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cloverIcon1 = lv_image_create(ui_slotColumn1);
lv_image_set_src(ui_cloverIcon1, &ui_img_clover_png);
lv_obj_set_width( ui_cloverIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cloverIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cloverIcon1, 0 );
lv_obj_set_y( ui_cloverIcon1, 120 );
lv_obj_set_align( ui_cloverIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cloverIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cloverIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_slotColumn2 = lv_obj_create(ui_Slots);
lv_obj_remove_style_all(ui_slotColumn2);
lv_obj_set_width( ui_slotColumn2, 61);
lv_obj_set_height( ui_slotColumn2, 101);
lv_obj_set_x( ui_slotColumn2, 69 );
lv_obj_set_y( ui_slotColumn2, -11 );
lv_obj_set_align( ui_slotColumn2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_slotColumn2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_slotColumn2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_slotColumn2, LV_DIR_VER);
lv_obj_set_style_pad_row(ui_slotColumn2, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_slotColumn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cloverIcon2 = lv_image_create(ui_slotColumn2);
lv_image_set_src(ui_cloverIcon2, &ui_img_clover_png);
lv_obj_set_width( ui_cloverIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cloverIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cloverIcon2, 0 );
lv_obj_set_y( ui_cloverIcon2, -120 );
lv_obj_set_align( ui_cloverIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cloverIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cloverIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sevenIcon2 = lv_image_create(ui_slotColumn2);
lv_image_set_src(ui_sevenIcon2, &ui_img_seven_png);
lv_obj_set_width( ui_sevenIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sevenIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_sevenIcon2, 2 );
lv_obj_set_y( ui_sevenIcon2, -60 );
lv_obj_set_align( ui_sevenIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_sevenIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_sevenIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heartIcon2 = lv_image_create(ui_slotColumn2);
lv_image_set_src(ui_heartIcon2, &ui_img_heart_png);
lv_obj_set_width( ui_heartIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heartIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heartIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_heartIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_heartIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barIcon2 = lv_image_create(ui_slotColumn2);
lv_image_set_src(ui_barIcon2, &ui_img_bar_png);
lv_obj_set_width( ui_barIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_barIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_barIcon2, 0 );
lv_obj_set_y( ui_barIcon2, 60 );
lv_obj_set_align( ui_barIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_barIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_barIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_cherryIcon2 = lv_image_create(ui_slotColumn2);
lv_image_set_src(ui_cherryIcon2, &ui_img_cherry_png);
lv_obj_set_width( ui_cherryIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cherryIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cherryIcon2, 0 );
lv_obj_set_y( ui_cherryIcon2, 120 );
lv_obj_set_align( ui_cherryIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cherryIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_cherryIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_actionBar = lv_image_create(ui_Slots);
lv_image_set_src(ui_actionBar, &ui_img_action_bar_png);
lv_obj_set_width( ui_actionBar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_actionBar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_actionBar, 0 );
lv_obj_set_y( ui_actionBar, 61 );
lv_obj_set_align( ui_actionBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_actionBar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_actionBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spinBtn = lv_imagebutton_create(ui_Slots);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_spin_red_png, NULL);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_spin_red_png, NULL);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_spin_gray_png, NULL);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_spin_red_png, NULL);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_spin_red_png, NULL);
lv_imagebutton_set_src(ui_spinBtn, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui_img_spin_gray_png, NULL);
lv_obj_set_height( ui_spinBtn, 53);
lv_obj_set_width( ui_spinBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_spinBtn, 0 );
lv_obj_set_y( ui_spinBtn, 60 );
lv_obj_set_align( ui_spinBtn, LV_ALIGN_CENTER );
lv_obj_add_state( ui_spinBtn, LV_STATE_CHECKED | LV_STATE_PRESSED );     /// States

ui_betBar = lv_image_create(ui_Slots);
lv_image_set_src(ui_betBar, &ui_img_bet_bar_png);
lv_obj_set_width( ui_betBar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_betBar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_betBar, -67 );
lv_obj_set_y( ui_betBar, 60 );
lv_obj_set_align( ui_betBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_betBar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_betBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_minusBtn = lv_imagebutton_create(ui_Slots);
lv_imagebutton_set_src(ui_minusBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_minus_btn_png, NULL);
lv_obj_set_height( ui_minusBtn, 30);
lv_obj_set_width( ui_minusBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_minusBtn, 49 );
lv_obj_set_y( ui_minusBtn, 60 );
lv_obj_set_align( ui_minusBtn, LV_ALIGN_CENTER );

ui_divider = lv_image_create(ui_Slots);
lv_image_set_src(ui_divider, &ui_img_divder_png);
lv_obj_set_width( ui_divider, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_divider, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_divider, 67 );
lv_obj_set_y( ui_divider, 60 );
lv_obj_set_align( ui_divider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_divider, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_divider, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_plusBtn = lv_imagebutton_create(ui_Slots);
lv_imagebutton_set_src(ui_plusBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_plus_btn_png, NULL);
lv_obj_set_height( ui_plusBtn, 30);
lv_obj_set_width( ui_plusBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_plusBtn, 86 );
lv_obj_set_y( ui_plusBtn, 60 );
lv_obj_set_align( ui_plusBtn, LV_ALIGN_CENTER );

ui_slotsLogo = lv_image_create(ui_Slots);
lv_image_set_src(ui_slotsLogo, &ui_img_slot_logo_png);
lv_obj_set_width( ui_slotsLogo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_slotsLogo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_slotsLogo, -1 );
lv_obj_set_y( ui_slotsLogo, -118 );
lv_obj_set_align( ui_slotsLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_slotsLogo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_slotsLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_backButtonSlots = lv_imagebutton_create(ui_Slots);
lv_imagebutton_set_src(ui_backButtonSlots, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_back_btn_png, NULL);
lv_imagebutton_set_src(ui_backButtonSlots, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui_img_back_btn_dis_png, NULL);
lv_obj_set_height( ui_backButtonSlots, 31);
lv_obj_set_width( ui_backButtonSlots, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_backButtonSlots, -92 );
lv_obj_set_y( ui_backButtonSlots, 128 );
lv_obj_set_align( ui_backButtonSlots, LV_ALIGN_CENTER );
lv_obj_set_style_image_recolor(ui_backButtonSlots, lv_color_hex(0x252525), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_image_recolor_opa(ui_backButtonSlots, 120, LV_PART_MAIN| LV_STATE_DISABLED);

ui_moneyBarSlots = lv_image_create(ui_Slots);
lv_image_set_src(ui_moneyBarSlots, &ui_img_money_bar_png);
lv_obj_set_width( ui_moneyBarSlots, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moneyBarSlots, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moneyBarSlots, 50 );
lv_obj_set_y( ui_moneyBarSlots, 128 );
lv_obj_set_align( ui_moneyBarSlots, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_moneyBarSlots, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_moneyBarSlots, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_coinAmountLabelSlots = ui_coinAmountLabelSlots_create(ui_Slots);
lv_obj_set_x( ui_coinAmountLabelSlots, 34 );
lv_obj_set_y( ui_coinAmountLabelSlots, 129 );

ui_betAmountSlots = ui_betAmountSlots_create(ui_Slots);
lv_obj_set_x( ui_betAmountSlots, -71 );
lv_obj_set_y( ui_betAmountSlots, 61 );

ui_jackpotImg = lv_image_create(ui_Slots);
lv_image_set_src(ui_jackpotImg, &ui_img_jackpotwin_png);
lv_obj_set_width( ui_jackpotImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_jackpotImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_jackpotImg, -3 );
lv_obj_set_y( ui_jackpotImg, 1 );
lv_obj_set_align( ui_jackpotImg, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_jackpotImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_opa(ui_jackpotImg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_spinBtn, ui_event_spinBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_minusBtn, ui_event_minusBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_plusBtn, ui_event_plusBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_slotsLogo, ui_event_slotsLogo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_backButtonSlots, ui_event_backButtonSlots, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slots, ui_event_Slots, LV_EVENT_ALL, NULL);

}
